# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: 김현아 # Website name
image:
  filename: "me.jpg"
  caption: "Image credit: [**Unsplash**](https://unsplash.com)"
baseURL: 'https://hyuunaaa.github.io/' # Website URL

# Site title and description
title: "김현아 - 전북대학교 컴퓨터공학부 김현아의 개발 이야기"
description: "전북대학교 컴퓨터공학부 김현아의 다양한 프로젝트와 연구 활동, 그리고 개발자 라이프를 공유하는 블로그입니다."

# Keywords for search engines
keywords: ["전북대학교", "컴퓨터공학", "개발자", "김현아", "웹 개발", "AI 연구", "개인 블로그"]

# Author name
author: "김현아"

# Open Graph settings (for social media previews)
params:
  description: "전북대학교 컴퓨터공학부 김현아의 개발 이야기와 다양한 프로젝트 소개"
  author: "김현아"
  ogImage: "me.jpg"  # 사이트를 대표하는 이미지의 경로
  ogType: "website"
  ogTitle: "효나 - 전북대학교 컴퓨터공학부 김현아의 개발 이야기"

instagram:
  username: "test"
  url: "https://www.instagram.com/"
############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################
build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep

